name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Build and publish package
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/deep-organizer/

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install packaging tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build setuptools wheel twine

      - name: Clean previous builds
        run: rm -rf dist build

      - name: Build distributions
        run: python -m build

      - name: Verify distribution metadata
        run: |
          python -m twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
